# Generated by Django 5.0.4 on 2024-04-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='latitude',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='longitude',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
