# Generated by Django 5.0.4 on 2024-04-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_coordinate_latitude_alter_coordinate_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
